name: Hourly PMC Stats Collector

on:
  schedule:
    - cron: '0 * * * *' # Chạy vào phút thứ 0 của mỗi giờ (0:00, 1:00, 2:00...)
  workflow_dispatch: # Cho phép bấm nút chạy thủ công để test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Dùng bản ổn định, không lo lỗi version 3.14 như máy bạn

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run script
        env: # Mở két sắt lấy Key ra dùng
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py
